name: Auto-Merge Owner's PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dallae'  # Replace with your username
    steps:
      - name: Enable Auto-Merge
        uses: actions/github-script@v7
        with:
          script: |
            // Enable auto-merge directly without approving
            await github.rest.pulls.enableAutomerge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'rebase'
            });
