name: Auto-Merge Owner's PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dallae'  # Replace with your username
    steps:
      - name: Enable Auto-Merge
        uses: actions/github-script@v7
        env:
          PAT: ${{ secrets.PAT }}  # Required for authentication
        with:
          script: |
            // Get pull request node ID
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            // GraphQL mutation to enable auto-merge
            await github.graphql(`
              mutation ($pullRequestId: ID!, $mergeMethod: PullRequestMergeMethod!) {
                enablePullRequestAutoMerge(input: {
                  pullRequestId: $pullRequestId,
                  mergeMethod: $mergeMethod
                }) {
                  clientMutationId
                }
              }
            `, {
              pullRequestId: pr.node_id,
              mergeMethod: "REBASE"  # Match your ruleset
            });
