name: Auto-Merge Owner's PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dallae' # Only run for PRs created by the user 'dallae'

    steps:
      # Log the github.actor value
      - name: Log github.actor
        run: echo "github.actor is ${{ github.actor }}"

      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Wait for all status checks to complete
      - name: Wait for Status Checks
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.PAT }}  # Required for authentication with a personal access token

      # Step 3: Verify that the pull request is mergeable and has the required approvals
      - name: Verify Mergeability
        id: checks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            console.log(`github.actor: ${{ github.actor }}`);

            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            // Check if the PR is mergeable
            if (pr.data.mergeable !== true) {
              core.setFailed("PR has merge conflicts or is not mergeable");
              return;
            }

            // Check for required approvals
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const approvals = reviews.data.filter(
              review => review.state === "APPROVED"
            );

            console.log(`Approvals count: ${approvals.length}`);

            // Ensure at least 1 approval is present if actor is not dallae
            if (approvals.length < 1 && '${{ github.actor }}' !== 'dallae') {
              core.setFailed("PR needs at least 1 approval");
            }

      # Step 4: Enable auto-merge for the pull request
      - name: Enable Auto-Merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            try {
              const { data: pr } = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number
              });

              await github.graphql(
                `mutation ($prId: ID!, $mergeType: PullRequestMergeMethod!) {
                  enablePullRequestAutoMerge(input: {
                    pullRequestId: $prId,
                    mergeMethod: $mergeType
                  }) { clientMutationId }
                }`,
                { prId: pr.node_id, mergeType: "REBASE" }
              );

              console.log("✅ Auto-merge enabled successfully");
            } catch (error) {
              core.setFailed(`❌ Auto-merge failed: ${error.message}`);
            }