name: Auto-Merge Owner's PRs

on:
  pull_request:
    types: [opened, reopened, synchronize]

# Add this permissions block
permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dallae'  # Replace with your username
    steps:
      - name: Auto-Approve PR
        uses: actions/github-script@v7
        env:
          PAT: ${{ secrets.PAT }}
        with:
          script: |
            // Auto-approve
            await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              event: 'APPROVE'
            });

            // Enable rebase merge
            await github.rest.pulls.enableAutomerge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              merge_method: 'rebase'
            });
