name: Validate Adblock List

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Adblock Syntax
        run: |
          # Allow: [Adblock header], standard rules (!, ||, ##), scriptlets (##+js), and element hiding
          INVALID_LINES=$(grep -vE '^(\[Adblock.*\]|!|@@|\|\||##\+js\(|##|#|\s*$)|^[^#!]+?##' ads-no-more.txt || true)
          if [ -n "$INVALID_LINES" ]; then
            echo "❌ Invalid syntax found. Valid patterns:"
            echo "  - Header: [Adblock Plus 2.0]"
            echo "  - Comments: ! ... (must not start with 'www')"
            echo "  - Blocking rules: ||domain.com/path"
            echo "  - Element hiding: ##selector or domain.com##selector"
            echo "  - Scriptlets: ##+js(...)"
            echo "  - Exceptions: @@||domain.com"
            echo "Invalid lines:"
            echo "$INVALID_LINES"
            exit 1
          fi

          # Check for comments starting with '! www'
          WWW_COMMENTS=$(grep -E '^! www' ads-no-more.txt || true)
          if [ -n "$WWW_COMMENTS" ]; then
            echo "❌ Comments starting with '! www' are invalid:"
            echo "$WWW_COMMENTS"
            echo "💡 Fix: Remove or reformat comments starting with '! www'."
            exit 1
          fi

          # Check for duplicates (case-insensitive, ignore comments and scriptlets)
          DUPLICATES=$(grep -vE '^[!\[#]' ads-no-more.txt | sort -f | uniq -id)
          if [ -n "$DUPLICATES" ]; then
            echo "❌ Case-insensitive duplicates found:"
            echo "$DUPLICATES"
            exit 1
          fi

          # Remaining checks (line endings, whitespace, newline)
          if grep -q $'\r' ads-no-more.txt; then
            echo "❌ Found CRLF line endings - use LF format"
            exit 1
          fi

          TRAILING_WS=$(grep -n '\s$' ads-no-more.txt || true)
          if [ -n "$TRAILING_WS" ]; then
            echo "❌ Trailing whitespace found:"
            echo "$TRAILING_WS"
            exit 1
          fi

          if [ -n "$(tail -c 1 ads-no-more.txt)" ]; then
            echo "❌ File must end with a newline"
            exit 1
          fi

          echo "✅ All checks passed!"